src/index.ts

Export PollingMode enum so it can be used in consuming apps

Export PollingMode

---

package.json

Set a less strict react version in `peerDependencies`

Update package.json - Set a less strict react version in `peerDependencies`

---

package-lock.json
package.json
tsconfig.json

Disabled sourcemap generation.

Disable sourcemap generation

---

package-lock.json
package.json
samples/react-sdk-sample/package-lock.json
samples/react-sdk-sample/package.json

December 2022 dependency updates

December 2022 dependency updates

---

sandbox/package-lock.json
sandbox/package.json
sandbox/src/stories/Hoc.tsx
sandbox/src/stories/Hook.tsx
src/ConfigCatHooks.tsx
src/ConfigCatProvider.tsx

fix user state issues

---

package-lock.json
package.json

Prepare v2.0.0 release

---

package-lock.json
package.json

Prepare v2.2.1 release

---

package-lock.json
package.json
src/ConfigCatHooks.tsx

Possible fix for https://github.com/configcat/react-sdk/issues/27

fix user state

---

package-lock.json
package.json
src/Cache.ts
src/ConfigCatHooks.test.tsx
src/ConfigCatProvider.test.tsx
src/ConfigCatProvider.tsx
src/index.ts

Update public type re-exports and fixes tests.

Adjust SDK to configcat-common v8.0

---

package-lock.json
package.json

Prepare v3.0.1 release

---

package-lock.json
package.json

Prepare v3.0.2 release
https://github.com/configcat/js-sdk/issues/81

Prepare v3.0.2 release

---

package-lock.json
package.json
src/index.ts

Prepare v3.1.0 release

---

package-lock.json
package.json

Prepare v3.1.1 release
Fixes:
* Downgrade TypeScript compiler version to v4.1 for better compatibility.

Prepare v3.1.1 release

---

package-lock.json
package.json

October 2023 security updates

---

package-lock.json
package.json
src/index.ts

Prepare v4.0.0 (Catnip) release

Prepare v4.0.0 (Catnip) release

---

samples/react-sdk-sample/package-lock.json
samples/react-sdk-sample/package.json
sandbox/package-lock.json
sandbox/package.json
sandbox/src/stories/Hook.tsx

Updated samples.
Provide links to issues relating to this pull request

Updated samples

---

.vscode/settings.json
package-lock.json
package.json

Prepare v4.4.0 release

---

package-lock.json

June 2024 security updates

---

package-lock.json
package.json

Prepare v4.6.1 release

---

package-lock.json
package.json

Prepare v4.9.0 release
n/a
n/a
n/a

Prepare v4.9.0 release
